famille/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.forms import PasswordChangeForm
from django.views.generic import TemplateView
from postman.views import WriteView, ReplyView
from tastypie.api import Api

from famille import resources
from famille.forms import CustomAuthenticationForm
from famille.utils.mail import email_moderation
from famille.views.web import ClaimSuccessView, Recover


admin.autodiscover()
api = Api(api_name='v1')
api.register(resources.PrestataireResource())
api.register(resources.FamilleResource())
api.register(resources.FamillePlanningResource())
api.register(resources.PrestatairePlanningResource())
api.register(resources.ScheduleResource())
api.register(resources.WeekdayResource())


urlpatterns = patterns(
    '',
    url(r'^$', "famille.views.home", name="home"),
    url(r'^in', 'django.contrib.auth.views.login', {
        'authentication_form': CustomAuthenticationForm
    }, name='auth_login'),
    url(r'^out/$', 'django.contrib.auth.views.logout', {
        'next_page': '/',
        'extra_context': {'action': 'logged_out'}
    }, name='auth_logout'),
    url(r'^mon-compte/$', 'famille.views.account', name="account"),
    url(r'^mon-compte/parametres-avances/', "famille.views.advanced", name="advanced"),
    url(
        r'^mon-compte/changer-de-mot-de-passe/$', 'django.contrib.auth.views.password_change',
        {
            'password_change_form': PasswordChangeForm,
            'post_change_redirect': '/mon-compte/parametres-avances/?success',
            'template_name': 'account/password_change.html'
        }, name="password_change"
    ),
    url(r'^mon-compte/suppression/$', 'famille.views.delete_account', name="delete_account"),
    url(r'^profile/(?P<type>[a-z]+)/(?P<uid>\d+)/$', "famille.views.profile", name="profile"),
    url(r'^devenir-premium/$', "famille.views.premium", name="premium"),
    url(r'^devenir-premium/succes/$', "famille.views.premium_success", name="premium_success"),
    url(r'^devenir-premium/annuler/$', "famille.views.premium_cancel", name="premium_cancel"),
    url(r'^recherche/$', 'famille.views.search', name="search"),
    url(r'^register(?:/(?P<social>[a-zA-Z]+)/((?P<type>[a-zA-Z]+)))?/$', 'famille.views.register', name="register"),
    url(r'^favorite/$', 'famille.views.favorite', name="favorite"),
    url(r'^tout-sur-la-garde-denfants/$', 'famille.views.tools', name="tools"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^recover/$', Recover.as_view(
        search_fields=["email"], email_template_name="password_reset/recovery_email.html",
        email_subject_template_name="password_reset/recovery_email_subject.txt"
    ), name='password_reset_recover'),
    # api
    url(r'^plannings/$', 'famille.views.plannings', name="plannings"),
    url(r'^profile-pic/$', 'famille.views.profile_pic', name="profile_pic"),
    url(r'^submit-rating/(?P<type>[a-z]+)/(?P<uid>\d+)/$', "famille.views.submit_rating", name="submit_rating"),
    url(r'^autocomplete/', "famille.views.message_autocomplete", name="message_autocomplete"),
    url(r'^signal-user/(?P<userType>[a-z]+)/(?P<uid>\d+)/$', "famille.views.signal_user", name="signal_user"),
    url(r'^contact-us/$', "famille.views.contact_us", name="contact_us"),
    url(r'^get-recipients/(?P<data>.+)/$', "famille.views.get_recipients", name="get_recipients"),
    url(r'^api/', include(api.urls)),

    # static pages
    url(
        r'^confirmation/$', TemplateView.as_view(template_name="confirmation.html"),
        name="confirmation"
    ),
    url(
        r'^espace-famille/$', TemplateView.as_view(template_name="espace/famille.html"),
        name="espace_famille"
    ),
    url(
        r'^espace-prestataire/$', TemplateView.as_view(template_name="espace/prestataire.html"),
        name="espace_prestataire"
    ),

    # plugin urls
    url(r'^grappelli/', include('grappelli.urls')),  # grappelli
    url(r'^tinymce/', include('tinymce.urls')),  # tinymce
    url('', include('social.apps.django_app.urls', namespace='social')),  # social auth
    url(r'^paypal/', include('paypal.standard.ipn.urls')),  # paypal
    url(r'', include('password_reset.urls')),  # password reset
    url(r'^messages/write/(?:(?P<recipients>[^/#]+)/)?$', WriteView.as_view(auto_moderators=email_moderation), name='postman_write'),
    url(r'^messages/reply/(?P<message_id>[\d]+)/$', ReplyView.as_view(auto_moderators=email_moderation), name='postman_reply'),
    url(r'^messages/', include('postman.urls')),  # postman
    url(
        r'^verification/(?P<group>[-\w]+)/(?P<key>[-\w]+)/success/$',
        ClaimSuccessView.as_view(), name='verification-success'
    ),  # verification
    url(r'^verification/', include('verification.urls')),  # verification
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

famille/admin/models.py
from django.contrib import admin
from django.contrib.flatpages.admin import FlatPageAdmin
from django.contrib.flatpages.models import FlatPage

from famille.admin import forms
from famille.models import Prestataire, Famille, DownloadableFile
from famille.utils import admin_display


class TinyMCEFlatPageAdmin(FlatPageAdmin):
    form = forms.TinyMCEForm


class BaseUserAdmin(admin.ModelAdmin):
    list_display = ('email', 'first_name', 'name', admin_display.pseudo_display, 'city', 'plan', 'is_active')
    list_display_links = ('email', )
    exclude = ('geolocation', )
    search_fields = ['first_name', 'name', 'email']
    list_filter = ('newsletter', )

    def is_active(self, obj):
        img = '<img src="/static/admin/img/icon-%s.gif" alt="%s">'
        params = ("yes", "True") if obj.user.is_active else ("no", "False")
        return img % params
    is_active.short_description = 'Actif'
    is_active.allow_tags = True


class FamilleAdmin(BaseUserAdmin):
    model = Famille
    form = forms.FamilleForm


class PrestataireAdmin(BaseUserAdmin):
    model = Prestataire
    form = forms.PrestataireForm


class DownloadableFileAdmin(admin.ModelAdmin):
    model = DownloadableFile
    form = forms.DownloadableFileForm
    list_display = ('name', 'file_type')
    search_fields = ['name', 'description']


# registering onto the admin site
admin.site.unregister(FlatPage)
admin.site.register(FlatPage, TinyMCEFlatPageAdmin)
admin.site.register(Famille, FamilleAdmin)
admin.site.register(Prestataire, PrestataireAdmin)
admin.site.register(DownloadableFile, DownloadableFileAdmin)

# TODO:
#       - display photo on rows ?
#       - a way to display plannings ?

famille/models.py
# -*- coding=utf-8 -*-
from itertools import imap

from django.contrib.auth.models import User
from django.db import models
from south.modelsinspector import add_introspection_rules

from famille.utils import parse_resource_uri, geolocation, fields as extra_fields
from famille.utils.mail import send_mail_from_template_with_noreply
from famille.utils.python import pick


class BaseModel(models.Model):
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    class Meta:
        abstract = True


class Geolocation(BaseModel):
    """
    A model that represent a geolocation
    of a user.
    """
    lat = models.FloatField()
    lon = models.FloatField()


def get_user_related(user):
    """
    Return the user related model. Either
    Famille or Prestataire.

    :param user:      Django user
    """
    try:
        return user.famille
    except Famille.DoesNotExist:
        return user.prestataire


class UserInfo(BaseModel):
    """
    The common user info that a Famille and
    a Prestataire need.
    """
    user = models.OneToOneField(User)
    geolocation = models.OneToOneField(Geolocation, blank=True, null=True)
    name = models.CharField(blank=True, max_length=50)
    first_name = models.CharField(blank=True, max_length=50)
    email = models.EmailField(max_length=100)

    street = models.CharField(blank=True, null=True, max_length=100)
    postal_code = models.CharField(blank=True, null=True, max_length=8)
    city = models.CharField(blank=True, null=True, max_length=40)
    country = models.CharField(blank=True, max_length=20, default="France")
    tel = models.CharField(blank=True, null=True, max_length=15)
    tel_visible = models.BooleanField(blank=True, default=False)


    class Meta:
        abstract = True

    def __unicode__(self):
        return unicode(self.__str__())

    def __str__(self):
        return self.name

    @property
    def is_geolocated(self):
        """
        A property to check if a user is geolocated.
        """
        return bool(self.geolocation)

    def geolocate(self):
        """
        Geolocate a user, using google geolocation.
        It basically calls the Google API and
        saves the GPS coordinates into database.

        NB: since geolocate is called in a pre_save signal,
            we do not save the model to save time, since
            it'll be saved soon enough.
        """
        address = "%s %s %s, %s" % (
            self.street or "",
            self.postal_code or "",
            self.city or "",
            self.country or ""
        )
        lat, lon = geolocation.geolocate(address)
        self.geolocation = Geolocation(lat=lat, lon=lon)
        self.geolocation.save()

    @staticmethod
    def _geolocate(sender, instance, **kwargs):
        """
        A signal receiver to geolocate a user whenever its
        data is saved.
        """
        if not instance.geolocation and any((instance.postal_code, instance.city)):
            instance.geolocate()

    def add_favorite(self, resource_uri):
        """
        Favorite an object for the user.

        :param resource_uri:          the URI of the resource to favorite
        """
        object_type, object_id = parse_resource_uri(resource_uri)
        self.favorites.get_or_create(object_type=object_type.title(), object_id=int(object_id))

    def remove_favorite(self, resource_uri):
        """
        Unfavorite an object for the user.

        :param resource_uri:      the URI of the resource to unfavorite
        """
        object_type, object_id = parse_resource_uri(resource_uri)
        object_type = object_type.title()
        object_id = int(object_id)
        self.favorites.filter(object_type=object_type, object_id=object_id).delete()

    def get_favorites_data(self):
        """
        Retrieve the favorites data.
        """
        # FIXME: can become greedy in the future
        return (favorite.get_user() for favorite in self.favorites.all())

    # FIXME: nothing to do here...
    def get_resource_uri(self):
        """
        Return the API uri of the objet. Don't really like it but for now
        didn't find another way.
        """
        return "/api/v1/%ss/%s" % (self.__class__.__name__.lower(), self.pk)

    # FIXME: cannot test it, cannot mock...
    def send_mail_to_favorites(self, message, favorites):
        FavoriteClass = FAVORITE_CLASSES[self.__class__]
        favorites = imap(lambda fav: pick(fav, "object_type", "object_id"), favorites)
        favorites = (FavoriteClass(**fav) for fav in favorites)
        # verify that the users are real favorites
        emails = (fav.get_user().email for fav in favorites if fav.owner == self)
        # remove possible None
        emails = filter(None, emails)

        if emails:
            send_mail_from_template_with_noreply(
                "email/contact_favorites.html", message,
                subject=message.get("subject", ""), recipient_list=emails
            )


class Criteria(UserInfo):
    TYPES_GARDE_FAMILLE = {
        "dom": "Garde à domicile",
        "part": "Garde partagée",
    }
    TYPES_GARDE = {
        "dom": "Garde à domicile",
        "part": "Garde partagée",
        "mat": "Garde par une assistante maternelle",
        "struct": "Structure d'accueil",
    }
    DIPLOMA = {
        "cap": "CAP Petite enfance",
        "deaf": u"Diplôme d'Etat Assistant(e) familial(e) (DEAF)",
        "ast": "Assistant maternel / Garde d'enfants",
        "deeje": u"Diplôme d'Etat d'éducateur de jeunes enfants (DEEJE)",
    }
    LANGUAGES = {
        "en": "Anglais",
        "de": "Allemand",
        "es": "Espagnol",
        "it": "Italien",
    }

    type_garde = models.CharField(blank=True, null=True, max_length=10, choices=TYPES_GARDE.items())
    diploma = models.CharField(blank=True, null=True, max_length=10, choices=DIPLOMA.items())
    menage = models.BooleanField(blank=True, default=False)
    repassage = models.BooleanField(blank=True, default=False)
    cdt_periscolaire = models.BooleanField(blank=True, default=False)
    sortie_ecole = models.BooleanField(blank=True, default=False)
    nuit = models.BooleanField(blank=True, default=False)
    non_fumeur = models.BooleanField(blank=True, default=False)
    devoirs = models.BooleanField(blank=True, default=False)
    urgence = models.BooleanField(blank=True, default=False)
    psc1 = models.BooleanField(blank=True, default=False)
    permis = models.BooleanField(blank=True, default=False)
    baby = models.BooleanField(blank=True, default=False)
    tarif = models.FloatField(blank=True, null=True)
    description = models.CharField(blank=True, null=True, max_length=400)

    class Meta:
        abstract = True


class Prestataire(Criteria):
    """
    The Prestataire user.
    """
    TYPES = {
        "part": "Particuliers",
        "pro": "Professionel indépendant"
    }
    LEVEL_LANGUAGES = {
        "deb": u"Débutant",
        "mid": u"Intermédiaire",
        "pro": u"Maîtrisé",
        "bil": "Bilingue"
    }
    RESUME_TYPES = {
        ".doc": "application/msword",
        ".pdf": "application/pdf",
        ".docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        ".pages": "application/x-iwork-pages-sffpages"
    }

    type = models.CharField(max_length=40, choices=TYPES.items())
    sub_types = models.CharField(max_length=40) # TODO choices

    language_kw = dict(blank=True, null=True, max_length=10, choices=LEVEL_LANGUAGES.items())
    level_en = models.CharField(**language_kw)
    level_de = models.CharField(**language_kw)
    level_es = models.CharField(**language_kw)
    level_it = models.CharField(**language_kw)
    other_language = models.CharField(blank=True, null=True, max_length=50)
    resume = extra_fields.ContentTypeRestrictedFileField(
        upload_to="resume", blank=True, null=True,
        content_types=RESUME_TYPES.values(), extensions=RESUME_TYPES.keys(),
        max_upload_size=2621440  # 2.5MB
    )


class Famille(Criteria):
    """
    The Famille user.
    """
    TYPE_FAMILLE = {
        "mono": "Famille monoparentale",
        "foyer": "Famille Mère/Père au foyer",
        "actif": "Famille couple actif",
    }

    type = models.CharField(blank=True, null=True, max_length=10, choices=TYPE_FAMILLE.items())
    type_presta = models.CharField(blank=True, null=True, max_length=10, choices=Prestataire.TYPES.items())
    langue = models.CharField(blank=True, max_length=10, choices=Prestataire.LANGUAGES.items())


class Enfant(BaseModel):
    """
    An child of a Famille.
    """
    famille = models.ForeignKey(Famille, related_name="enfants")
    # compelled to do this naming because we cannot change the form field names...
    e_name = models.CharField(max_length=20, db_column="name")
    e_birthday = models.DateField(blank=True, null=True, db_column="birthday")
    e_school = models.CharField(blank=True, null=True, max_length=50, db_column="school")


class BasePlanning(BaseModel):
    """
    A planning entry.
    """
    FREQUENCY = {
        "all": "Tous les jours",
        "week": "Tous les jours en semaine",
        "hebdo": "Hebdomadaire",
        "2week": "Toute les 2 semaines",
        "month": "Tous les mois"
    }
    start_date = models.DateTimeField()
    end_date = models.DateTimeField(blank=True, null=True)
    frequency = models.CharField(blank=True, null=True, max_length=10, choices=FREQUENCY.items())
    comment = models.CharField(blank=True, null=True, max_length=50)

    class Meta:
        abstract = True


class FamillePlanning(BasePlanning):
    famille = models.ForeignKey(Famille, related_name="planning")


class PrestatairePlanning(BasePlanning):
    prestataire = models.ForeignKey(Prestataire, related_name="planning")


class BaseFavorite(BaseModel):
    """
    A model reprensenting a favorite.
    """
    OBJECT_TYPES = {
        'Prestataire': 'Prestataire',

famille/admin/forms.py
from django import forms
from django.contrib.flatpages.admin import FlatpageForm
from django.contrib.flatpages.models import FlatPage
from tinymce.widgets import TinyMCE

from famille.models import Famille, Prestataire, DownloadableFile


class TinyMCEForm(FlatpageForm):
    class Meta:
        model = FlatPage
        widgets = {
            'content': TinyMCE(attrs={'cols': 100, 'rows': 30}, content_language="fr")
        }


class UserForm(forms.ModelForm):
    class Meta:
        widgets = {
            "description": forms.Textarea()
        }

class FamilleForm(forms.ModelForm):
    class Meta(UserForm.Meta):
        model = Famille


class PrestataireForm(forms.ModelForm):
    class Meta(UserForm.Meta):
        model = Prestataire


class DownloadableFileForm(forms.ModelForm):
    class Meta:
        model = DownloadableFile
        widgets = {
            "description": forms.Textarea()
        }

famille/templates/profile/401.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}
{% load helpers %}

{% block title %}404{% endblock %}

{% block content %}
<div class="col-md-12">
    <div class="row">
        <div class="page-header col-md-10 col-md-offset-1">
            <div class="col-xs-4 col-md-2">
                <a href="#" class="thumbnail">
                    <img src="{% static "img/nopic.png" %}" alt="Photo de profil">
                </a>
            </div>
            <h1>Cet utilisateur <small>a décidé de cacher son profil</small></h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="quatre">401</div>
        </div>
    </div>
</div>
{% endblock %}

famille/templates/profile/famille.html
{% extends "profile/base.html" %}
{% load staticfiles %}
{% load static %}
{% load helpers %}
{% load users %}

{% block subtitle %}
{% with nb_enfants=profile.enfants.all.count %}
{% if nb_enfants %}
<h2>
    {{ nb_enfants }} enfant{% if nb_enfants > 1%}s{% endif %}
</h2>
{% endif %}
{% endwith %}
{% endblock %}

{% block contentBlock1 %}  <!-- infos générales -->
    <h5 class="title-profil"><span class="glyphicon glyphicon-list-alt"></span> Attentes générales</h5>
    <div class="form-group">
        <p>
        <a class="label-profil"> Type de prestataire :</a> {% if profile.type_presta %}{{ profile.get_type_presta_display }}{% else %}--{% endif %}
        </p>
    </div>
    <div class="form-group">
        <p><a class="label-profil"> Type de garde :</a> {% multi_display profile.type_garde "type_garde" %}</p>
    </div>
    <div class="form-group">
        <p><a class="label-profil"> Tarif souhaité :</a> {{ profile.tarif|display_tarif }} €/h</p>
    </div>
{% endblock %}

{% block contentBlock2 %}  <!-- enfants -->
{% with nb_enfants=profile.enfants.all.count %}
{% if nb_enfants %}
    <h5 class="title-profil">Les enfants</h5>
    <ul>
        {% for enfant in profile.enfants.all %}
        <li>{{ enfant.display }}</li>
        {% endfor %}
    </ul>
{% endif %}
{% endwith %}
{% endblock %}

{% block block3Title %}<span class="glyphicon glyphicon-check"></span> Mes besoins{% endblock %}

{% block contentBlock4 %}  <!-- petits plus -->
            <h5  class="title-profil"><span class="glyphicon glyphicon-plus"></span> Les p'tits plus recherchés</h5>
            <div class="row">
                <div class="col-md-3 text-center">
                    <div class="row">
                        <img src="{% static profile|badge_icon:'repassage' %}" width="60px">
                    </div>
                    <div class="row">
                        Repassage
                    </div>
                </div>
                <div class="col-md-3 text-center">
                    <div class="row">
                        <img src="{% static profile|badge_icon:'menage' %}" width="60px">
                    </div>
                    <div class="row">
                        Ménage
                    </div>
                </div>
                <div class="col-md-3 text-center">
                    <div class="row">
                        <img src="{% static profile|badge_icon:'non_fumeur' %}" width="60px">
                    </div>
                    <div class="row">
                        Non fumeur
                    </div>
                </div>
                <div class="col-md-3 text-center">
                    <div class="row">
                        <img src="{% static profile|badge_icon:'cuisine' %}" width="60px">
                    </div>
                    <div class="row">
                        Cuisine
                    </div>
                </div>
            </div>
            <div class="row margin-top-little">
                <div class="col-md-3 text-center">
                    <div class="row">
                        <img src="{% static profile|badge_icon:'enfant_malade' %}" width="60px">
                    </div>
                    <div class="row">
                        Expérience avec les enfants handicapés
                    </div>
                </div>
                <div class="col-md-3 text-center">
                    <div class="row">
                        <img src="{% static profile|badge_icon:'animaux' %}" width="60px">
                    </div>
                    <div class="row">
                        Amis des animaux
                    </div>
                </div>
                <div class="col-md-3 text-center">
                    <div class="row">
                        <img src="{% static profile|badge_icon:'psc1' %}" width="60px">
                    </div>
                    <div class="row">
                        Formation aux premiers secours
                    </div>
                </div>
                <div class="col-md-3 text-center">
                    <div class="row">
                        <img class=none"" src="{% static profile|badge_icon:'devoirs' %}" width="60px">
                    </div>
                    <div class="row">
                        Aide aux devoirs
                    </div>
                </div>
            </div>
            <div class="row margin-top-little">
                <div class="col-md-3 text-center">
                    <div class="row">
                        <img class=none"" src="{% static profile|badge_icon:'permis' %}" width="60px">
                    </div>
                    <div class="row">
                        Permis voiture
                    </div>
                </div>
            </div>
            {% endblock %}

{% block block5Title %}<span class="glyphicon glyphicon-comment"></span> Plus de détails sur notre famille{% endblock %}

{% block extra %}
<span data-field="resource_uri" class="hidden">/api/v1/familles/{{ profile.pk }}/</span>
{% endblock %}

famille/templates/profile/prestataire.html
{% extends "profile/base.html" %}
{% load static %}
{% load staticfiles %}
{% load helpers %}
{% load users %}

{% block subtitle %}
    <h2>
    {% if profile.get_age %}
      {{ profile.get_age }} ans
    {% endif %}
    <small>
      {{ profile.get_type.upper }}
    </small>
    </h2>
{% endblock %}

{% block extra-header %}
{% if profile.resume %}
<a class="btn btn-color btn-brown-min btn-block" href="{% get_media_prefix %}{{ profile.resume }}" target="_blank">
    <span class="glyphicon glyphicon-file"></span> CV
</a>
{% else %}
<em>Cet utilisateur n'a pas encore renseigné son CV</em>
{% endif %}
{% endblock %}

{% block contentBlock1 %}  <!-- infos générales -->
    <h5  class="title-profil"><span class="glyphicon glyphicon-list-alt"></span> Informations générales</h5>
    <div class="form-group">
        <p><a class="label-profil"> Type de garde:</a> {% multi_display profile.type_garde "type_garde" %}</p>
    </div>
    <div class="form-group">
        <p><a class="label-profil"> Tarif:</a> {{ profile.tarif|display_tarif }} €/h</p>
    </div>
{% endblock %}

{% block block3Title %}<span class="glyphicon glyphicon-check"></span> Mes compétences{% endblock %}

{% block contentBlock4 %}  <!-- petits plus -->
            <h5  class="title-profil"><span class="glyphicon glyphicon-plus"></span> Mes p'tits plus</h5>
            <div class="row">
                <div class="col-md-3 text-center">
                    <div class="row">
                        <img src="{% static profile|badge_icon:'repassage' %}" width="60px">
                    </div>
                    <div class="row">
                        J'accepte de faire du repassage
                    </div>
                </div>
                <div class="col-md-3 text-center">
                    <div class="row">
                        <img src="{% static profile|badge_icon:'menage' %}" width="60px">
                    </div>
                    <div class="row">
                        J'accepte de faire du ménage
                    </div>
                </div>
                <div class="col-md-3 text-center">
                    <div class="row">
                        <img src="{% static profile|badge_icon:'non_fumeur' %}" width="60px">
                    </div>
                    <div class="row">
                        Je ne fume pas
                    </div>
                </div>
                <div class="col-md-3 text-center">
                    <div class="row">
                        <img src="{% static profile|badge_icon:'cuisine' %}" width="60px">
                    </div>
                    <div class="row">
                        Je sais cuisiner
                    </div>
                </div>
            </div>
            <div class="row margin-top-little">
                <div class="col-md-3 text-center">
                    <div class="row">
                        <img src="{% static profile|badge_icon:'enfant_malade' %}" width="60px">
                    </div>
                    <div class="row">
                        Je m'occupe d'enfants handicapés
                    </div>
                </div>
                <div class="col-md-3 text-center">
                    <div class="row">
                        <img src="{% static profile|badge_icon:'animaux' %}" width="60px">
                    </div>
                    <div class="row">
                        Je m'occupe de vos animaux
                    </div>
                </div>
                <div class="col-md-3 text-center">
                    <div class="row">
                        <img src="{% static profile|badge_icon:'psc1' %}" width="60px">
                    </div>
                    <div class="row">
                        Formation aux premiers secours
                    </div>
                </div>
                <div class="col-md-3 text-center">
                    <div class="row">
                        <img class=none"" src="{% static profile|badge_icon:'devoirs' %}" width="60px">
                    </div>
                    <div class="row">
                        J'aide vos enfants dans leur devoirs
                    </div>
                </div>
            </div>
            <div class="row margin-top-little">
                <div class="col-md-3 text-center">
                    <div class="row">
                        <img class=none"" src="{% static profile|badge_icon:'permis' %}" width="60px">
                    </div>
                    <div class="row">
                        J'ai une voiture
                    </div>
                </div>
            </div>
            {% endblock %}

{% block block5Title %}Plus de détails sur moi{% endblock %}

{% block contentBlock6 %}  <!-- references -->
<h5  class="title-profil"><span class="glyphicon glyphicon-comment"></span> Mes références</h5>
{% for reference in profile.references.all %}
<div class="row">
    <div class="col-md-8">
        <h5>Avec la famille {{ reference.get_famille_display }} <small>{{ reference.get_dates_display }}</small></h5>
        {% if reference.garde != "Autre" %}
        <p>Garde de type {{ reference.get_garde_display }}</p>
        {% endif %}
        <p>Mission(s) éffectuée(s):</p>
        <p>{{ reference.missions }}</p>
    </div>
</div>
{% empty %}
<p>Cette utilisateur n'a pas encore rempli ses références.</p>
{% endfor %}
{% endblock %}

{% block extra %}
<span data-field="resource_uri" class="hidden">/api/v1/prestataires/{{ profile.pk }}/</span>
{% endblock %}